arch: M2FTrans
classifier: ConvClassifierNorm
cls_layers: 2
conv_dims: 16
transformer_dims: ~
num_heads: 8
mlp_dim: 4096
depth: 3
dropout_rate: 0.1
proj_drop: 0.
img_size: 64
patch_size: 4
region_prompt: False
modal_prompt: False
modal: ~
labels: ~
num_cls: ~
fusion_type: ~