arch: mmFormer
classifier: ConvClassifierNorm
cls_layers: 2
conv_dims: 8
transformer_dims: 512
num_heads: 8
mlp_dim: 4096
depth: 1
dropout_rate: 0.1946634841787338
proj_drop: 0.1946634841787338
img_size: 64
patch_size: 4
region_prompt: False
modal_prompt: False
modal: ~
labels: ~
num_cls: ~
fusion_type: ~