arch: RFNetOrig
classifier: ~
cls_layers: 2
conv_dims: 16
transformer_dims: ~
num_heads: ~
mlp_dim: ~
depth: ~
dropout_rate: 0.1946634841787338
proj_drop: 0.1946634841787338
img_size: 64
patch_size: 4
region_prompt: False
modal_prompt: False
modal: ~
labels: ~
num_cls: ~
fusion_type: ~