name: "GliomaPost"
test_name: "GliomaPost"
img_size: ~
labels: null
train_path: null
val_path: null
test_path: "/projectnb/ivc-ml/dlteif/MU-Glioma-Post/MU-Glioma-Post_npy/test.txt"
inflate: False
stripped: ~
modal: ["flair","t1","t1ce","t2"]
load_segmentations: ~
apply_mask: null
random_masking: False
split_ratio: 0.0
seed: ~