defaults:
  - override hydra/sweeper: wandb

hydra:
  sweeper:
    wandb_sweep_config:
      name: mmformer_sweep_test

      method: bayes

# (Optional) Specify the metric to optimize (only used by certain search
      # strategies and stopping criteria). Default is {}.
      metric:
        name: Val/loss
        goal: minimize

        # (Optional) Goal value for the metric you're optimizing. When any run
        # in the sweep achieves that target value, the sweep's state will be set
        # to finished. This means all agents with active runs will finish those
        # jobs, but no new runs will be launched in the sweep.
        # target: 0.0

      # (Optional) Number of agents to launch in a batch until budget is
      # reached. Use a multi-processing launcher to have these agents execute
      # simultaneously, otherwise it's a useless option since they'll execute in
      # sequence. Default is 1.
      num_agents: 1

      # (Optional) Total number of agents to launch (must be >= num_agents)
      # Default is 1.
      budget: 1

      # (Optional) Specify the entity for this sweep. Otherwise infer from the
      # environment.
      # entity: your_entity

      # (Optional) Specify the project this sweep will be under. Projects are
      # used to organize models that can be compared, working on the same
      # problem with different architectures, hyperparameters, datasets,
      # preprocessing etc. Default is None.
      project: MultiModalMRI

      # (Optional) Notes can contain a string, a list, or any
      # OmegaConf-compatible value. Notes are added to all runs and show up in
      # the W&B UI for each run. Since notes can also be modified from within
      # the W&B UI, they're meant to be used for noting runs with extra info
      # _after_ they have finished. Default is None.
      notes: ${hydra.overrides.task}

      # (Optional) Tags can be used to label runs from an agent with particular
      # features, such as the runs being pre-emptible. They make it easier to
      # filter runs in the W&B UI. Default is [].
      tags:
        - ${model.arch}
        - ${model.classifier}
        - ${model.region_prompt}
        - ${model.modal_prompt}
        - ${region_prompt.embed_module}
        - ${modal_prompt.embed_module}

      # (Optional) Specify any early stopping criteria. Default is {}.
      early_terminate:
        type: hyperband
        min_iter: 3
        # max_iter: 27  #  the maximum number of iterations.
        # s: 2  # the total number of brackets (required for max_iter)
        eta: 3  # the bracket multiplier schedule

      # (Optional) Number of function evaluations to perform per agent
      # Recommended to set to 1 when running in SLURM environment.
      # Each agent only runs one training job then exits. Default is 1.
      count: 1

      # (Optional) Maximum authorized failure rate for a batch of wandb agents'
      # runs. Default is 0.0.
      max_run_failure_rate: 0.3

      # (Optional) Maximum authorized failure rate for a batch of wandb agents
      # launched by the launcher. Default is 0.0.
      max_agent_failure_rate: 0.1

      # (Optional) Used for resuming from a previous sweep. Default is None.
      # sweep_id: your_sweep_id

    # (Required) Specify parameters bounds to search.
    # Parameters are described using dot notation but will be accessible within
    # the task function in typical OmegaConf fashion,
    # e.g., model_param1 = cfg.model.param1
    params:
      # Categorical, one or the other
      model.classifier:
        - ConvClassifierNorm
        - TransformerSACLSHead

      train.augment:
        value: "RegionModalMix1.1"

      train.cont_alpha:
        distribution: q_log_uniform
        min: 0.01
        max: 1
        q: 2.0

      train.cont_beta:
        distribution: q_log_uniform
        min: 0.01
        max: 1
        q: 2.0

      # A log-distributed positive scalar, evolving by factors of 2 on average
      optimizer.params.lr:
        distribution: q_log_uniform
        min: 0.02
        max: 1
        q: 2.0

      # A linearly-distributed scalar between 0 and 1
      model.dropout_rate:
        distribution: uniform
        min: 0.1
        max: 1.0

      # A linearly-distributed integer scalar between 4 to 16
      train.batch_size:
        distribution: int_uniform
        min: 2
        max: 8

      train.accum_iter:
        distribution: int_uniform
        min: 2
        max: 8